# Generated by Django 3.1.2 on 2020-10-04 11:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diary",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Name")),
                ("start_date", models.DateField(verbose_name="Startdatum")),
                ("end_date", models.DateField(verbose_name="Enddatum")),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        srid=4326, verbose_name="Ort"
                    ),
                ),
            ],
        ),
    ]
