# Generated by Django 3.1.3 on 2020-11-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20201010_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='entry_pics', verbose_name='Bilder'),
        ),
    ]
