# Generated by Django 3.2.20 on 2023-12-14 21:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_auto_20231210_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='entry_pics'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='entry_pics', validators=[django.core.validators.FileExtensionValidator(['blp', 'bmp', 'dib', 'bufr', 'cur', 'pcx', 'dcx', 'dds', 'ps', 'eps', 'fit', 'fits', 'fli', 'flc', 'ftc', 'ftu', 'gbr', 'gif', 'grib', 'h5', 'hdf', 'png', 'apng', 'jp2', 'j2k', 'jpc', 'jpf', 'jpx', 'j2c', 'icns', 'ico', 'im', 'iim', 'jfif', 'jpe', 'jpg', 'jpeg', 'mpg', 'mpeg', 'tif', 'tiff', 'msp', 'pcd', 'pxr', 'pbm', 'pgm', 'ppm', 'pnm', 'psd', 'qoi', 'bw', 'rgb', 'rgba', 'sgi', 'ras', 'tga', 'icb', 'vda', 'vst', 'webp', 'wmf', 'emf', 'xbm', 'xpm', 'mp4', 'mov'])], verbose_name='Bilder'),
        ),
    ]
