# Generated by Django 3.1.2 on 2020-10-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diary_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Enddatum'),
        ),
    ]
