# Generated by Django 3.1.2 on 2020-10-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_auto_20201007_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='participants',
        ),
    ]
